### ISSUE TITLE
Automatic warning for API Key expiry

### ISSUE THREAD

**Issue by routerino** [gurucomputing/headscale-ui#10]
Create the capability to warn when an API key is about to expire. Create a button in the server settings to roll over an API key automatically. Create a toggle to show or hide the api key.

**Comment by LOVEChen** [comment]
At the same time, I think this problem can be solved simply by creating an apikey with a super long date? LOL

headscale apikeys create --expiration 3650d

**Comment by routerino** [comment]
> At the same time, I think this problem can be solved simply by creating an apikey with a super long date? LOL
> 
> headscale apikeys create --expiration 3650d

bad security. Longer expiries lead to greater chance of the API key being compromised. Having a convenient way to roll over the keys is a better option.
