### ISSUE TITLE
can add split page function to devices list?

### ISSUE THREAD

**Issue by linxd** [gurucomputing/headscale-ui#100]
when there are many nodes, the  devices page display more in a page , splitting  page may be a good way

**Comment by routerino** [comment]
are you encountering performance issues? I would expect the page to scale to thousands of nodes before impacting a modern browser. If you need to filter down, that's what the search filter is for.

**Comment by routerino** [comment]
Gonna close as stale (at least until someone tells me they have 10,000+ nodes)
