### ISSUE TITLE
Can't use digits when creating new user in the web ui

### ISSUE THREAD

**Issue by Gallium70** [gurucomputing/headscale-ui#103]
** Supporting Details **
Provide the following:
* Browser Version: Chromium  112.0.5615.121
* Headscale Version: 0.22.3
* Any Browser Errors (`control+shift+i` in chrome to see)

**Describe the bug**

When I tried creating a new user with digits in the username, a popup says "Use lower case letters, periods, or dashes only". However I could create a user with the same name in the headscale CLI (`headscale users create`), and this user could be displayed in the web UI properly. Seems that this username format is checked at the frontend rather than enforced by the headscale server. Should the username format restriction be consistent between the web UI and headscale server?

**Comment by routerino** [comment]
I believe that restriction might be a holdover from a previous headscale version. Also yes, inpouts are checked (ideally) at both front and back end.

I'll fix it up and release a new version in the next couple of days.
