### ISSUE TITLE
Headscale URL & API Key

### ISSUE THREAD

**Issue by Ejz9** [gurucomputing/headscale-ui#111]
** Supporting Details **
Provide the following:
* Browser Version: Opera: latest
* Headscale Version: latest
* Any Browser Errors (`control+shift+i` in chrome to see): None from what I see.

**Describe the Issue**

I've setup headscale using their base docker-compose. The UI site loads just fine. I did have to mess around and create a config for headscale itself but after a container restart all is well. Although, I am struggling to connect headscale-UI to headscale. I am able to get my headscale API key. I cannot however get my headscale URL to work. I have it listening on 0.0.0.0:27896 and the URL I've been trying to have as 0.0.0.0:27896 or localhost ...etc. Regardless, after multiple attempts when trying to allow the two services to connect with each other, I cannot get the URL to work. I've skimmed your guide as well and I just cannot get past this. Nor does anything regarding headscale exist when I browse the URL it says it's on in the config.

I'm not an expert but I feel as though It's only a matter of pointing A to B yet there's some conflict... Any Help! Thanks!

**Comment by ithakaa** [comment]
Same issue

**Comment by routerino** [comment]
Headscale ui is not tested with ports or IPs, you will break CORS.

```
HS-UI has to be ran on the same subdomain or you need to configure CORS. Yes you need to use a reverse proxy to do this. Use a reverse proxy.
```

**Comment by routerino** [comment]
Closed with https://github.com/gurucomputing/headscale-ui/commit/88012147d3a43b556f38ad8ff8e44d236f07d763
