### ISSUE TITLE
please delete

### ISSUE THREAD

**Issue by ithakaa** [gurucomputing/headscale-ui#113]
please delete this, stupid error on my part

**Comment by routerino** [comment]
I can see you're using IP instead of a reverse proxy. How to guide isn't going to help if you can't get past the front page readme.

> HS-UI has to be ran on the same subdomain as headscale or you need to configure CORS. Yes you need to use a reverse proxy to do this. Use a reverse proxy. If you are trying to use raw IPs and ports, it will not work.

**Comment by ithakaa** [comment]
I've conducted sufficient testing to confirm that the issue persists whether we use IP addresses (which, as you've explained, shouldn't be used due to CORS, and I understand that) or domain names.

New nodes integrate with headscale without any issues and operate as intended. However, there's an ongoing problem where the Headscale-UI fails to establish a connection with the headscale server, even though the API keys are valid.

I've also involved a colleague in this matter, and they have reached the same outcome: the UI remains unable to establish a connection with the headscale server.

**Comment by routerino** [comment]
Are you using separate subdomains for headscale and headscale-ui or are you serving them both on the same subdomain?

**Comment by ithakaa** [comment]
Same domain, different path for the UI /web

**Comment by routerino** [comment]
Theoretically there shouldn't be anything else you have to accomplish.

You can review [this guide](https://blog.gurucomputing.com.au/Smart%20VPNS%20with%20Headscale/Configuring%20the%20Headscale%20UI/) to see if that provides more insight onto where it's falling over.

**Comment by ithakaa** [comment]
Thanks, I have come across that guide and although helpful still doesn't resolve the issue

Since my last message, another colleague, this makes it three, have attempted and failed to get the UI to integrate with headscale.

Really not sure where to turn now but if others have tried without success, they may have just abandoned the idea of using headache-ui which i personally believe is a great tool
