### ISSUE TITLE
accessing headscale server on same lan over http (not https)

### ISSUE THREAD

**Issue by hs6666** [gurucomputing/headscale-ui#116]
hi,

i've just setup my first headscale server on the oracle free tier, everything works ok, server is at 10.0.0.26

i've another oracle cloud VM at 10.0.0.8 (with a desktop gui installed) and docker installed, and have installed headscale-ui on this server

i then created a new api key on the headscale server using the command "tailscale apikey create"

i then went into the headscale ui settings and entered this key with the url as....  http://10.0.0.26:8080

but its not connecting, does it have to be https please?

thanks

Harry

**Comment by routerino** [comment]
Yes, it has to be https and must be using a domain name to satisfy browser API requirements.
