### ISSUE TITLE
WebUI Login Security by Authentik or Token

### ISSUE THREAD

**Issue by masterwishx** [gurucomputing/headscale-ui#127]
Using Lasted version of HeadScale in Docker + headscale-ui + Nginx Proxy Manager.
is any way to secure login to webUI maybe by Authentik or some Token?
i tryed but cant make it work behind Authentik.

**Comment by routerino** [comment]
Yes in the sense that you can secure any web application via an oauth proxy. No in that it is not necessary. See https://github.com/gurucomputing/headscale-ui?tab=readme-ov-file#cross-domain-installation

**Comment by masterwishx** [comment]
> Yes in the sense that you can secure any web application via an oauth proxy. No in that it is not necessary. See https://github.com/gurucomputing/headscale-ui/blob/master/SECURITY.md#authentication-and-authorization

Thanks, i got it. 
Also i saw its using local storage of browser ,  its not a big problem but tried to proxy access to /web page by Authentik.
but it seems not working in regular way like for other apps are working ...
using Nginx Proxy Manager + Authentik.

**Comment by masterwishx** [comment]
can be  `return 301 https://$host/web;` added to /admin location in Nginx Proxy Manager ,is it safe ?

![image](https://github.com/gurucomputing/headscale-ui/assets/28630321/a8d03d3a-458f-4989-90fb-ed55e6d6cd72)

**Comment by routerino** [comment]
Closing due to no replies within 30 days and as a general cleanup
