### ISSUE TITLE
404 on GET https://<domain>/api/v1/machine

### ISSUE THREAD

**Issue by Benjlr** [gurucomputing/headscale-ui#130]
** Supporting Details **
Provide the following:
* Browser Version: Version 121.0.6167.185 (Official Build) (64-bit)
* 
* Headscale Version:  0.23.0-alpha4
* 
* Any Browser Errors (`control+shift+i` in chrome to see)
* 
GET https://<domain>/api/v1/machine 404 (Not Found)
window.fetch @ start-101bf427.js:1
(anonymous) @ apiFunctions-60f89b05.js:1
(anonymous) @ apiFunctions-60f89b05.js:1
m @ apiFunctions-60f89b05.js:1
Rt @ apiFunctions-60f89b05.js:1
(anonymous) @ _page.svelte-ad198750.js:1
(anonymous) @ _page.svelte-ad198750.js:1
o @ _page.svelte-ad198750.js:1
(anonymous) @ _page.svelte-ad198750.js:1
tt @ index-a1abfc0f.js:1
(anonymous) @ index-a1abfc0f.js:4
_t @ index-a1abfc0f.js:4
Promise.then (async)
ft @ index-a1abfc0f.js:4
Lt @ index-a1abfc0f.js:4
(anonymous) @ index-a1abfc0f.js:4
a.$$set @ start-101bf427.js:1
$set @ index-a1abfc0f.js:4
De @ start-101bf427.js:1
await in De (async)
ie @ start-101bf427.js:1
(anonymous) @ start-101bf427.js:1
apiFunctions-60f89b05.js:1 Uncaught (in promise) {"code":5, "message":"Not Found", "details":[]}
o @ apiFunctions-60f89b05.js:1
Promise.then (async)
l @ apiFunctions-60f89b05.js:1
(anonymous) @ apiFunctions-60f89b05.js:1
m @ apiFunctions-60f89b05.js:1
Rt @ apiFunctions-60f89b05.js:1
(anonymous) @ _page.svelte-ad198750.js:1
(anonymous) @ _page.svelte-ad198750.js:1
o @ _page.svelte-ad198750.js:1
(anonymous) @ _page.svelte-ad198750.js:1
tt @ index-a1abfc0f.js:1
(anonymous) @ index-a1abfc0f.js:4
_t @ index-a1abfc0f.js:4
Promise.then (async)
ft @ index-a1abfc0f.js:4
Lt @ index-a1abfc0f.js:4
(anonymous) @ index-a1abfc0f.js:4
a.$$set @ start-101bf427.js:1
$set @ index-a1abfc0f.js:4
De @ start-101bf427.js:1
await in De (async)
ie @ start-101bf427.js:1
(anonymous) @ start-101bf427.js:1

**Describe the bug**
A 404 Not Found response is received for any action on the endpoint api/v1/machine

![image](https://github.com/gurucomputing/headscale-ui/assets/16767196/080d01ec-8ce2-425f-bdc3-e968118c98f5)

**Comment by danktankk** [comment]
I have this same issue

**Comment by Benjlr** [comment]
I found out that this issue is documented in  #115, and will not be resolved until the next production headscale release. I will close this issue.
