### ISSUE TITLE
Device view fails (tested with headscale docker image 0.23.0)

### ISSUE THREAD

**Issue by lhb-cafe** [gurucomputing/headscale-ui#131]
I am able to load User View without problems. So the connection to server should be fine and the API key testing should be successful.
But the Device View page fails with the following error pop-up:
        {"code":5,"message":"Not Found","details":[]}

I suspect this might be a compatibility issue with the latest headscale docker image (tag 0.23.0, which was released about a week ago). Please advise. Many thanks!

**Comment by olerap** [comment]
Also experiencing this problem. Running headscale 23.0.
