### ISSUE TITLE
An error when test server key

### ISSUE THREAD

**Issue by yoshiakiley** [gurucomputing/headscale-ui#138]
Can't use with headscale/headscale:0.23.0-alpha5
when Test Server Config, there is a log print: ERR home/runner/work/headscale/headscale/hscontrol/app.go:380 > missing "Bearer " prefix in "Authorization" header client_address=172.17.0.1:45110

**Comment by routerino** [comment]
No bug reports will currently be accepted for interactions with the headscale alpha, I'll update the front page to reflect that.

FYI I have tested with both alpha and current versions so it's not a version incompatibility issue.
