### ISSUE TITLE
Headscale dropped docker tag for headscale:latest

### ISSUE THREAD

**Issue by KenyOS** [gurucomputing/headscale-ui#143]
I was following the guide on readme and I found error while docker-compose pull the latest tag on headscale docker image, and I found the reason below the explanation. From now on.. stable version should be tagged on release version.

[https://github.com/juanfont/headscale/issues/1810](https://github.com/juanfont/headscale/issues/1810)

**Comment by routerino** [comment]
I definitely don't agree with their reasoning behind dropping the `latest` tag, saying it's "not best practice" seems more of a "we screwed up the `latest` tag convention and so we're going to blame the tag instead of using it right".

That said, yes, I'll update the blog :).

**Comment by routerino** [comment]
Fixed the readme up in #154
