### ISSUE TITLE
Changes in LastSeen / Online fields in the Headscale API

### ISSUE THREAD

**Issue by juanfont** [gurucomputing/headscale-ui#144]
Hey!

Headscale dev here. Just a small heads up.

Since 0.23.0-alpha8, LastSeen is only updated when the node disconnects. This means the Online is now the indicator if the node is connected to headscale or not.

Of course, once a node is offline you can display the LastSeen data.

**Comment by routerino** [comment]
Resolved with #150 (thanks @ChxGuillaume )
