### ISSUE TITLE
Feature request: Set exit node

### ISSUE THREAD

**Issue by acheong08** [gurucomputing/headscale-ui#146]
https://headscale.net/exit-node/#on-the-node

**Comment by routerino** [comment]
Any features are dependent on the headscale API supporting it.

**Comment by routerino** [comment]
Based on a look through the newest doco, it looks like the exit node feature is just an extension of routes, which is already an existing feature. There is no way for the server to create routes that aren't advertised by the exit node so there's nothing for the UI to do.
