### ISSUE TITLE
Does a non-Docker version of this exist?

### ISSUE THREAD

**Issue by bmullan** [gurucomputing/headscale-ui#147]
Thought I'd ask as some organizations can't or won't use docker.

**Comment by routerino** [comment]
Yes, under releases there is a zip file containing the static web content. Just host it with your favorite web server (caddy, nginx, apache, iis if you're masochistic).

Note that you will need to reverse proxy onto the same subdomain as headscale because of CORS.

**Comment by bmullan** [comment]
@routerino 

when you said "_reverse proxy onto the same subdomain as headscale because of CORS_"

if the Headscale network is 172.16.x.x/12

did you mean reverse proxy to/from 172.16.x.x/12 and my Host Server's 192.168.x.x ?
