### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'innerHTML')

### ISSUE THREAD

**Issue by WoChen5770** [gurucomputing/headscale-ui#148]
The browser and headscale are both up to date.

<img width="723" alt="image" src="https://github.com/gurucomputing/headscale-ui/assets/26268544/1e00a3ff-2749-49db-a063-f37d1400a58d">

<img width="1760" alt="image" src="https://github.com/gurucomputing/headscale-ui/assets/26268544/bd192664-9172-4f3d-8d0e-b8a6806b9c66">

**Comment by routerino** [comment]
I can't recreate this issue, but I do not test against international languages.

If you have a pull request that can fix the problem I'll likely merge and push a new release.

**Comment by routerino** [comment]
Without any additional information, I'll assume that this is not reproducible.
