### ISSUE TITLE
no update for beta version of hds v.0.23?

### ISSUE THREAD

**Issue by linxd** [gurucomputing/headscale-ui#149]
** Supporting Details **
Provide the following:
* Browser Version: 
* Headscale Version: 0.23-beta1
* Any Browser Errors (`control+shift+i` in chrome to see)

** Note **
No bug reports are currently being accepted against the alpha version of headscale. Test against the production/stable version.

**Describe the bug**
A clear and concise description of what the bug is. Screenshots if applicable
updating  node status is not correct,

**Comment by graphixillusion** [comment]
hs 0.23 final is just released. i think the main dev of this project will update this asap too.

**Comment by routerino** [comment]
Yep, I'm on holiday at the moment but it's on my priority list when I get back.
