### ISSUE TITLE
Can not get device router

### ISSUE THREAD

**Issue by plusls** [gurucomputing/headscale-ui#167]
** Supporting Details **
Provide the following:
* Browser Version: edge
* Headscale Version: 64323e49c52a034d57867383549a51c65dfeddd6
* Any Browser Errors (`control+shift+i` in chrome to see) `GET https://xxxx:10443/api/v1/machine/14/routes 404 (Not Found)`

**Describe the bug**

Default, headscaleAPIMachineOrNode is null, so it use `machine` as the router query path.

https://github.com/gurucomputing/headscale-ui/blob/64323e49c52a034d57867383549a51c65dfeddd6/src/lib/devices/DeviceCard/DeviceRoutesAPI.svelte#L9

https://github.com/gurucomputing/headscale-ui/blob/64323e49c52a034d57867383549a51c65dfeddd6/src/lib/common/apiFunctions.svelte#L159

**Comment by MadWalnut** [comment]
`machine` needs to be updated to `node`, see #120

**Comment by routerino** [comment]
The machine or node check was removed, but clearly some references to machine got missed. Getting taken care of now
