### ISSUE TITLE
no connection headscale-ui and headscale

### ISSUE THREAD

**Issue by xyleyx** [gurucomputing/headscale-ui#183]
I run headscale, headscale-ui with the nginx proxy manager via docker. I can access the headscal ui but I can't reach headscale, a red X appears so I can't save the API key. SyntaxError: The string did not match the expected appears briefly. What did I miss configuring?![image](https://github.com/user-attachments/assets/0a8762ac-628f-41a3-9eca-8ff8445e9c4b)

**Comment by MatKlein** [comment]
Nice to see that I'm not alone. I struggle with the same error pattern no matter what I try.

**Comment by fabriziohobi** [comment]
same setup and error here

**Comment by xyleyx** [comment]
<img width="1090" alt="Bildschirmfoto 2024-12-20 um 15 34 12" src="https://github.com/user-attachments/assets/ac86d390-eacb-4b13-a3da-c53c07d5598a" />


I solved the problem in my case! To do this, I entered the following CORS headers in the corresponding location block for the API (/api). This is necessary to allow cross-origin requests from the UI to the API.

location /api {
    add_header Access-Control-Allow-Origin *;
    add_header Access-Control-Allow-Methods "GET, POST, OPTIONS";
    add_header Access-Control-Allow-Headers "Authorization, Content-Type";

    ## Weiterleitung an die Headscale-API
    proxy_pass http://headscale:8080/api;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    ## Real-IP Einstellungen
    set_real_ip_from 172.20.0.0/16;
    real_ip_header X-Forwarded-For;

    ## Timeout Einstellungen
    send_timeout 5m;
    proxy_read_timeout 240;
    proxy_send_timeout 240;
    proxy_connect_timeout 240;
}
