### ISSUE TITLE
Improve documentation to explain how to create an API key and save it in the settings

### ISSUE THREAD

**Issue by pageb018** [gurucomputing/headscale-ui#20]
Trying to stand this up and am not able to connect ui to headscale. Receiving the following in log out 

`headscale     | 2022-08-03T14:06:35Z ERR go/src/headscale/app.go:348 > missing "Bearer " prefix in "Authorization" header client_address=172.27.0.1:34438`

Maybe this has to do with my nginx proxy settings, but am not sure. 

Not sure how to process, any ideas?

**Comment by routerino** [comment]
Missing bearer prefix means that the API key is either missing or malformed. Have you generated an API key in headscale and saved it to your settings? If so, there may be a problem with your proxy config.

**Comment by routerino** [comment]
closing unless/until problem can be recreated.

**Comment by Sloth-on-meth** [comment]
same error here, even though api key is created and shows up when i list them

**Comment by routerino** [comment]
what browser and version of headscale are you using?

**Comment by routerino** [comment]
When updating the documentation, also add the tooltip explaning localStorage back to "save api key", as it got lost when shuffling around the button settings.
