### ISSUE TITLE
Please match the requested format 

### ISSUE THREAD

**Issue by LefflerMediaLLC** [gurucomputing/headscale-ui#21]
When trying to add the server it says 'Please match the requested format' my domain is `https://headscale.domain.network`. Is `.network` not considered a TLD in the code?

**Comment by routerino** [comment]
The input is theoretically tied to a domain regex, but I'll test yours tomorrow and see if it doesn't meet the criteria. If not I'll have to find a better representative algorithm.

**Comment by routerino** [comment]
I can confirm that I can enter `https://headscale.domain.network` as is, can you provide an example where it doesn't work?

<img width="415" alt="image" src="https://user-images.githubusercontent.com/45954722/182727110-517c7e42-3d21-4eff-9f1f-4fde8d9d43ad.png">

**Comment by routerino** [comment]
Closing unless/until problem can be recreated.
