### ISSUE TITLE
Some questions and suggestions about headscale-ui

### ISSUE THREAD

**Issue by LOVEChen** [gurucomputing/headscale-ui#36]
Question 1:
The ip of the docker network name cannot be obtained, and the format is incorrect.
The network inside the virtual machine is actually accessible by direct name

PING headscale (172.30.0.2): 56 data bytes
64 bytes from 172.30.0.2: seq=0 ttl=42 time=0.081 ms
64 bytes from 172.30.0.2: seq=1 ttl=42 time=0.058 ms

PING headscale-ui (172.30.0.3): 56 data bytes
64 bytes from 172.30.0.3: seq=0 ttl=42 time=0.033 ms
64 bytes from 172.30.0.3: seq=1 ttl=42 time=0.037 ms

Can you consider supporting formats like http://headscale:8080?

Question 2:
http://172.30.0.2:8080 and the apikey is filled in, the verification cannot be passed
Request supports local authentication and http authentication

Question 3:
Can headscale-ui support output on port 80?
My signature is hung on nginx and then proxied back, and I don't need headscale-ui to have its own signature.

Many thanks.

**Comment by routerino** [comment]
For Question 1, you might be misunderstanding how the UI works. The docker container doesn't do any direct communication to headscale. All requests leave and arrive via your browser, and your browser definitely _isn't_ inside a docker container.

Question 2 not really sure what you're asking for here. If you need additional authentication methods you can put in a forward auth proxy. Anything more sophisticated is only feasible with a backend authentication platform, and headscale UI is frontend only.

Question 3, I default to https as a security measure. You can make a custom `caddyfile` and place it in `/data/Caddyfile` via a bind mount if you want a non-secure connection. I may redo the caddyfile to use caddy's JSON at some point so I can be more sophisticated about environment variables.

**Comment by routerino** [comment]
I'll close for now, Question 3 will be addressed with #37

**Comment by LOVEChen** [comment]
![CleanShot 2022-08-11 at 13 53 49](https://user-images.githubusercontent.com/7329959/184072099-7928f5a6-d436-400c-8843-d6a869567ac0.png)
![CleanShot 2022-08-11 at 13 54 12](https://user-images.githubusercontent.com/7329959/184072152-8328b264-d4d5-4b36-bbe2-76772b0a8c72.png)

Authentication failed, but browser access is no problem

**Comment by routerino** [comment]
Can you tell me what the console error says when this happens? You can find out by opening the dev console (control+shift+i) and reading out the error.

_theoretically_ what you are trying to do should work, but it all works on the browser `fetch` method, which sometimes gets unhappy with insecure sites. I suspect you're having CORS problems because the browser doesn't think it's the same domain.

**Comment by LOVEChen** [comment]
```
headscale must be served over TLS/HTTPS
Remote access does not support unencrypted traffic.
```

thanks bro 
i found this comment on headscale project ， problem resolve
