### ISSUE TITLE
Sort by ID doesn't sort numerically

### ISSUE THREAD

**Issue by justyns** [gurucomputing/headscale-ui#43]
When you have more than 9 nodes, the sort by ID looks like it is not sorting correctly.  E.g.: ID 3 ends up after ID 25.  

Example screenshot:

![image](https://user-images.githubusercontent.com/215985/184514599-d8c74483-1a6e-44af-b339-894bfaae57f4.png)

(thanks for making this UI!)

**Comment by routerino** [comment]
Ah yep, that'll be because the IDs are strings, even though they are actually numbers. I'll have to rethink how those get sorted.
