### ISSUE TITLE
Trim tailing slash in `Headscale URL` field

### ISSUE THREAD

**Issue by korfuri** [gurucomputing/headscale-ui#46]
Minor issue: if `Headscale URL` is filled to include a trailing `/`, this causes the requests to Headscale to be of the form `https://server//api/...` which returns 404s.

Options:

* Assuming that headscale-ui is indeed served from `/web/` and heascale's API is at `/`, this could be auto-configured;
* The UI should hint that trailing `/`s are probably unnecessary, or
* The trailing `/` should be trimmed automatically

Thanks!

**Comment by routerino** [comment]
I'm not actually getting this issue. I can configure the app to remove the trailing slash regardless (probably not a terrible idea), but I can't recreate the problem either.
