### ISSUE TITLE
Add an authentication

### ISSUE THREAD

**Issue by xuzhonglin** [gurucomputing/headscale-ui#57]
As headscale's admin console, I recommend that you add authentication before entering the console page, as this will make the service insecure if it is exposed to the public.

**Comment by routerino** [comment]
Any sensitive data is saved locally to the browser, so it does not expose sensitive information.

You can test by saving the key and opening the same site in incognito mode.

A proper OIDC based system would be better, but not feasible without a compatible backend.

**Comment by xuzhonglin** [comment]
I tested what you said and proved that you are absolutely right.
