### ISSUE TITLE
 missing "Bearer " prefix in "Authorization" header 

### ISSUE THREAD

**Issue by bulolo** [gurucomputing/headscale-ui#59]
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/10026498/188366043-5310ceba-737e-4bff-89c2-0e92a4e9b464.png">

<img width="1068" alt="image" src="https://user-images.githubusercontent.com/10026498/188366077-7371f7c9-7c44-4614-9c56-6e2d4b8df97d.png">

<img width="654" alt="image" src="https://user-images.githubusercontent.com/10026498/188366568-ad0b9fe6-211f-40bd-b815-df808a760f31.png">

**Comment by routerino** [comment]
CORS problem, browser won't send headers over http to another domain.
