### ISSUE TITLE
enable device routes fail when change advertise-routes in tailscale client

### ISSUE THREAD

**Issue by starskyzheng** [gurucomputing/headscale-ui#67]
** Supporting Details **
Provide the following:
* Browser Version:
edge
* Headscale Version:
0.16.4
* Any Browser Errors (`control+shift+i` in chrome to see)

**Describe the bug**
A clear and concise description of what the bug is. Screenshots if applicable

This happend when a tailscale client changes its advertise-routes using 'tailscale up --advertise-routes xxx --rest'.
The web browser can correctly shows device routes but cannot enable nor disable one of the device routes.
Seems like the list of device routes in headscale-ui server were not update after we changed 'advertise-routes' settings. And reboot the headscale-ui docker server can fix this problem.

**Comment by routerino** [comment]
the state of headscale-ui only updates on refresh or sort. I may add a poll option in the future, but without websockets there is no real time update of state.

Short answer is if you aren't sure, refresh.

**Comment by starskyzheng** [comment]
What is the meaning of 'refresh'? Means restart docker server of headscale UI? Or some button or shell command?

**Comment by routerino** [comment]
![image](https://user-images.githubusercontent.com/45954722/191862708-cc2850ff-5cec-4a9b-9012-9390a16559b2.png)
