### ISSUE TITLE
Use caddy as certificate manager

### ISSUE THREAD

**Issue by jsbrain** [gurucomputing/headscale-ui#79]
So apparently there's a way to [use caddy with headscale as certificate manager](https://caddyserver.com/docs/caddyfile/directives/tls#issuer:~:text=(or%20your%20open%20source%20Headscale%20server)%3B) so certificates can automatically be issued for service.

I do think this would interfere with the headscale-ui caddy configuration as if I'm understanding it correctly, to use this feature, headscale would need to be enabled to issue let's encrypt certificates or it won't work.

I might be mistaken but I do think this would require an alternative deployment/configuration of headscale-ui to make this work?

**Comment by routerino** [comment]
at the end of the day headscale-ui is a static http site. Anything that the browser will complain about for https will also complain about headscale-ui.

There might be a way but it's out of scope of how headscale-ui works.
