### ISSUE TITLE
Add Auth Login Page to UI 

### ISSUE THREAD

**Issue by mtate713** [gurucomputing/headscale-ui#80]
Could you add a login page in front the /web page? And maybe add 2FA or OAuth Support? I was experimenting with this on a cloud VPS, and I was thinking about how to protect it since I'm hosting Headscale and the UI remotely

**Comment by routerino** [comment]
security considerations are covered in https://github.com/gurucomputing/headscale-ui/blob/master/SECURITY.md

**Comment by mtate713** [comment]
Thank you! I really appreciate the Headscale UI and the other tutorials that you made!
