### ISSUE TITLE
device list, arrow cannot be closed

### ISSUE THREAD

**Issue by yangboyd** [gurucomputing/headscale-ui#82]
** Supporting Details **
Provide the following:
* Browser Version:
Chrome  94.0.4606.61
* Headscale Version:
*0.17.1+
* Any Browser Errors (`control+shift+i` in chrome to see)
_page.svelte-8213986a.js:formatted:1085 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at Object.p (_page.svelte-8213986a.js:formatted:1085)
    at Ot (index-4a5d41f3.js:formatted:483)
    at ft (index-4a5d41f3.js:formatted:458)

**Describe the bug**
The right-up side arrow does not work. It cannot be closed.
![image](https://user-images.githubusercontent.com/37931362/207311149-1c6496b3-ad2f-4068-983d-0930210cca13.png)

**Comment by routerino** [comment]
Interesting, I'm not seeing this bug. Maybe it's a problem with foreign characters?

I've been lax on maintenance so I'll push a new updated with the latest version of svelte, and see if that improves the issue. Anything you can provide to help recreate the problem would help.

**Comment by yangboyd** [comment]
It's for the latest headscale. That's route api changed.
I create a pull request for this https://github.com/gurucomputing/headscale-ui/pull/83.
