### ISSUE TITLE
Latest Headscale Beta API breaks Headscale-UI

### ISSUE THREAD

**Issue by Leen15** [gurucomputing/headscale-ui#84]
** Supporting Details **
Provide the following:
* Browser Version: Google Chrome
* Headscale Version: 0.18-beta1
* Any Browser Errors (`control+shift+i` in chrome to see)
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at Object.p (_page.svelte-8213986a.js:1:15519)
    at Ot (index-4a5d41f3.js:4:1456)
    at ft (index-4a5d41f3.js:4:1142)
```
**Describe the bug**
If I try to open a Device with the dropdown button or just pressing on the row, I get a console error and the UI stops working. Only a refresh can make the UI working again.

**Comment by routerino** [comment]
Known issue, the API isn't set in stone and thus upstream changes can break the API. Once headscale 18 leaves beta I'll put in a lock-step patch.
