### ISSUE TITLE
Blank page without a saved api key

### ISSUE THREAD

**Issue by Leen15** [gurucomputing/headscale-ui#86]
** Supporting Details **
Provide the following:
* Browser Version: Google Chrome
* Headscale Version: the last one
* Any Browser Errors (`control+shift+i` in chrome to see)

**Describe the bug**
I just upgraded to last version, finally it works.
Unfortunately if you try to open it in a browser where there isn't a key saved (or in incognito mode), it only shows a blank screen without any error in console.
Can you please check?
Thanks

**Comment by routerino** [comment]
This is what I get when I open up incognito:

![image](https://user-images.githubusercontent.com/45954722/209306662-c38dd7b3-6b8e-44a1-abfa-e41800570490.png)

**Comment by Leen15** [comment]
Sorry, my fault. It was just a misconfiguration in the root path of the domain.
Thank you.
