### ISSUE TITLE
Regression in legacy API for enabling multiple routes

### ISSUE THREAD

**Issue by drag0n141** [gurucomputing/headscale-ui#87]
* Browser Version: Google Chrome 108
* Headscale Version: 0.16.1

**Describe the bug**
I can not activate more than one route with the newest version. With the old version this works without any problem.

**Comment by routerino** [comment]
bleh, thought I tested for that in the old version. I'll re-test and see what went wrong.

**Comment by drag0n141** [comment]
No thats not the reason :) New Version of Headscale does not work with Traefik in front, thanks for fixing this so fast :D
