### ISSUE TITLE
Unable to connect to the server, F12 prompts 502 error

### ISSUE THREAD

**Issue by MilkTeaNo7** [gurucomputing/headscale-ui#90]
** Supporting Details **
Provide the following:
* Browser Version:Microsoft Edge 109.0.1518.52

* Headscale Version:headscale_0.18.0-beta3_linux_amd64
* Any Browser Errors (`control+shift+i` in chrome to see)
502错误

**Describe the bug**
He can display the homepage of headscale-ui, but he cannot add a server. The following is my nginx configuration. I suspect that it is his problem. Can anyone help me?

`server {
    #listen 80;
    listen 443 ssl;
    #server_name 192.168.80.21;
    #server_name 192.168.80.21:8080;

    ssl_certificate /etc/nginx/SSL/fullchain.crt;
    ssl_certificate_key /etc/nginx/SSL/privkey.key;

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 5m;
    keepalive_timeout 70;

    location / {
        proxy_redirect off;
        proxy_pass http://127.0.0.1:8080; # port
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /web {
        alias /html/headscale-ui/web;
        try_files $uri $uri/ /index.html;
    }

}`

**Comment by routerino** [comment]
Looks like the latest headscale broke the API for adding servers via the machine key.

**Comment by hhrhhr** [comment]
Rename namespace in protobuf files
https://github.com/juanfont/headscale/commit/428d7c86ce789148e985b1afd8e3568ff216caf0

**Comment by lyuly** [comment]
hi, boy. If you use caddy, you can write this Caddyfile. Headscale-ui docker listen `8088:80`, headscale docker listen `8081:8080`. For security, port 8088 and 8081 you can use firewall block outside traffic. Hope this is helpful for you.😁
```Caddyfile
https://example:443 {
    reverse_proxy /web* http://127.0.0.1:8088

    reverse_proxy * http://127.0.0.1:8081
}
```

**Comment by routerino** [comment]
I wasn't clear if this issue was a byproduct of #93 , however I will be closing it for now unless more details can be provided.
