### ISSUE TITLE
Add Headscale 0.19 support (namespace vs. user)

### ISSUE THREAD

**Issue by maltegrosse** [gurucomputing/headscale-ui#93]
Finally headscale switched from namespace to user, see https://github.com/juanfont/headscale/releases/tag/v0.19.0

Is it possible to switch the parameter, as `namespace` is deprecated from [v0.19.0-beta2](https://github.com/juanfont/headscale/releases/tag/v0.19.0-beta2). , see https://github.com/juanfont/headscale/commit/8dadb045cfa0148bf7c8da8cf434f1535e889d14

**Comment by routerino** [comment]
Yep, number of different API fixes I'll have to stick in. This will be a breaking change for the UI.

**Comment by maltegrosse** [comment]
as headscale is below version v.1, and headscale-ui containers are tagged, I dont see big issues about breaking changes yet...but perhaps I am wrong... I assume there will be alot of changes in headscale during the next months according to its activity and popularity.

**Comment by maltegrosse** [comment]
thanks for the PR and release @routerino . Seems the latest container tag has a typo: `2032.01.30-beta` should be `2023...`

**Comment by routerino** [comment]
bleh, yeah I'll update.
