### ISSUE TITLE
404 error when saving API Key on /api/v1/apikey

### ISSUE THREAD

**Issue by markhaur** [gurucomputing/headscale-ui#98]
Only saving Headscale API Key without mentioning Headscale URL is generating 404 error after calling /api/v1/apikey endpoint. I'm setting up Headscale and Headscale-UI on my local machine.
![image](https://user-images.githubusercontent.com/40026186/217421689-bfdf3867-7720-4ee8-b135-4b17ad027ede.png)

**Comment by routerino** [comment]
1. Don't include your bearer token in plain text in screenshots
2. You will encounter strange behavior if you are using an IP address and port as opposed to a domain. CORS *theoretically* can work that way but I do not test for it. see https://github.com/gurucomputing/headscale-ui#errors-related-to-missing-bearer-prefix

**Comment by routerino** [comment]
closing due to no reply
